-- =====================================================================
-- TurismoUQ — 02_tablas.sql
-- Ejecutar conectado como: turismouq@//localhost:1521/XEPDB1
-- Crea las 14 entidades obligatorias con PK, FK, CHECK, NOT NULL, UNIQUE.
-- Ver docs/00_modelo_ER.md para la justificación de cada decisión de diseño.
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. MUNICIPIO
-- ---------------------------------------------------------------------
CREATE TABLE municipio (
  id_municipio  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  nombre        VARCHAR2(60) NOT NULL,
  CONSTRAINT uq_municipio_nombre UNIQUE (nombre)
);

-- ---------------------------------------------------------------------
-- 2. TIPO_ALOJAMIENTO
-- ---------------------------------------------------------------------
CREATE TABLE tipo_alojamiento (
  id_tipo      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  nombre       VARCHAR2(40) NOT NULL,
  descripcion  VARCHAR2(200),
  CONSTRAINT uq_tipo_alojamiento_nombre UNIQUE (nombre)
);

-- ---------------------------------------------------------------------
-- 3. ALOJAMIENTO
-- ---------------------------------------------------------------------
CREATE TABLE alojamiento (
  id_alojamiento          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  id_municipio            NUMBER NOT NULL,
  id_tipo                 NUMBER NOT NULL,
  nombre                  VARCHAR2(120) NOT NULL,
  direccion               VARCHAR2(200),
  capacidad_max           NUMBER NOT NULL,
  calificacion_promedio   NUMBER(3,2) DEFAULT 0 NOT NULL,
  fecha_registro          DATE DEFAULT SYSDATE NOT NULL,
  estado                  VARCHAR2(15) DEFAULT 'ACTIVO' NOT NULL,
  CONSTRAINT fk_alojamiento_municipio FOREIGN KEY (id_municipio) REFERENCES municipio (id_municipio),
  CONSTRAINT fk_alojamiento_tipo FOREIGN KEY (id_tipo) REFERENCES tipo_alojamiento (id_tipo),
  CONSTRAINT ck_alojamiento_capacidad CHECK (capacidad_max > 0),
  CONSTRAINT ck_alojamiento_calificacion CHECK (calificacion_promedio BETWEEN 0 AND 5),
  CONSTRAINT ck_alojamiento_estado CHECK (estado IN ('ACTIVO','INACTIVO'))
);

-- ---------------------------------------------------------------------
-- 4. HABITACION
-- ---------------------------------------------------------------------
CREATE TABLE habitacion (
  id_habitacion    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  id_alojamiento   NUMBER NOT NULL,
  numero           VARCHAR2(10) NOT NULL,
  tipo_habitacion  VARCHAR2(20) NOT NULL,
  capacidad        NUMBER NOT NULL,
  estado           VARCHAR2(15) DEFAULT 'DISPONIBLE' NOT NULL,
  CONSTRAINT fk_habitacion_alojamiento FOREIGN KEY (id_alojamiento) REFERENCES alojamiento (id_alojamiento),
  CONSTRAINT uq_habitacion_numero UNIQUE (id_alojamiento, numero),
  CONSTRAINT ck_habitacion_capacidad CHECK (capacidad > 0),
  CONSTRAINT ck_habitacion_tipo CHECK (tipo_habitacion IN ('INDIVIDUAL','DOBLE','TRIPLE','SUITE','FAMILIAR')),
  CONSTRAINT ck_habitacion_estado CHECK (estado IN ('DISPONIBLE','MANTENIMIENTO','INACTIVA'))
);

-- ---------------------------------------------------------------------
-- 5. TEMPORADA  (filas concretas por año — ver decisión de diseño 2)
-- ---------------------------------------------------------------------
CREATE TABLE temporada (
  id_temporada    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  nombre          VARCHAR2(60) NOT NULL,
  tipo            VARCHAR2(10) NOT NULL,
  fecha_inicio    DATE NOT NULL,
  fecha_fin       DATE NOT NULL,
  factor_ajuste   NUMBER(4,2) NOT NULL,
  CONSTRAINT ck_temporada_tipo CHECK (tipo IN ('BAJA','MEDIA','ALTA')),
  CONSTRAINT ck_temporada_fechas CHECK (fecha_fin >= fecha_inicio),
  CONSTRAINT ck_temporada_factor CHECK (factor_ajuste > 0)
);

-- ---------------------------------------------------------------------
-- 6. TARIFA
-- ---------------------------------------------------------------------
CREATE TABLE tarifa (
  id_tarifa      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  id_habitacion  NUMBER NOT NULL,
  id_temporada   NUMBER NOT NULL,
  valor_noche    NUMBER(10,2) NOT NULL,
  CONSTRAINT fk_tarifa_habitacion FOREIGN KEY (id_habitacion) REFERENCES habitacion (id_habitacion),
  CONSTRAINT fk_tarifa_temporada FOREIGN KEY (id_temporada) REFERENCES temporada (id_temporada),
  CONSTRAINT uq_tarifa_habitacion_temporada UNIQUE (id_habitacion, id_temporada),
  CONSTRAINT ck_tarifa_valor CHECK (valor_noche > 0)
);

-- ---------------------------------------------------------------------
-- 7. CLIENTE
-- ---------------------------------------------------------------------
CREATE TABLE cliente (
  id_cliente         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  tipo_documento     VARCHAR2(5) NOT NULL,
  numero_documento   VARCHAR2(20) NOT NULL,
  nombre             VARCHAR2(60) NOT NULL,
  apellido           VARCHAR2(60) NOT NULL,
  email              VARCHAR2(120) NOT NULL,
  telefono           VARCHAR2(20),
  fecha_registro     DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT uq_cliente_documento UNIQUE (tipo_documento, numero_documento),
  CONSTRAINT uq_cliente_email UNIQUE (email),
  CONSTRAINT ck_cliente_tipo_doc CHECK (tipo_documento IN ('CC','CE','PA','TI'))
);

-- ---------------------------------------------------------------------
-- 8. RESERVA  (tabla histórica -> tablespace dedicado)
-- ---------------------------------------------------------------------
CREATE TABLE reserva (
  id_reserva       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  id_cliente       NUMBER NOT NULL,
  fecha_reserva    DATE DEFAULT SYSDATE NOT NULL,
  fecha_checkin    DATE NOT NULL,
  fecha_checkout   DATE NOT NULL,
  estado           VARCHAR2(15) DEFAULT 'PENDIENTE' NOT NULL,
  valor_total      NUMBER(12,2) DEFAULT 0 NOT NULL,
  CONSTRAINT fk_reserva_cliente FOREIGN KEY (id_cliente) REFERENCES cliente (id_cliente),
  CONSTRAINT ck_reserva_fechas CHECK (fecha_checkout > fecha_checkin),
  CONSTRAINT ck_reserva_estado CHECK (estado IN ('PENDIENTE','CONFIRMADA','CANCELADA','FINALIZADA')),
  CONSTRAINT ck_reserva_total CHECK (valor_total >= 0)
) TABLESPACE ts_historico_reservas;

-- ---------------------------------------------------------------------
-- 9. RESERVA_HABITACION  (asociativa N:M — ver decisión de diseño 1)
-- ---------------------------------------------------------------------
CREATE TABLE reserva_habitacion (
  id_reserva     NUMBER NOT NULL,
  id_habitacion  NUMBER NOT NULL,
  num_huespedes  NUMBER NOT NULL,
  valor_estadia  NUMBER(12,2) NOT NULL,
  CONSTRAINT pk_reserva_habitacion PRIMARY KEY (id_reserva, id_habitacion),
  CONSTRAINT fk_reshab_reserva FOREIGN KEY (id_reserva) REFERENCES reserva (id_reserva),
  CONSTRAINT fk_reshab_habitacion FOREIGN KEY (id_habitacion) REFERENCES habitacion (id_habitacion),
  CONSTRAINT ck_reshab_huespedes CHECK (num_huespedes > 0),
  CONSTRAINT ck_reshab_valor CHECK (valor_estadia >= 0)
) TABLESPACE ts_historico_reservas;

-- ---------------------------------------------------------------------
-- 10. PAGO
-- ---------------------------------------------------------------------
CREATE TABLE pago (
  id_pago             NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  id_reserva          NUMBER NOT NULL,
  fecha_pago          DATE DEFAULT SYSDATE NOT NULL,
  monto               NUMBER(12,2) NOT NULL,
  metodo_pago         VARCHAR2(20) NOT NULL,
  estado              VARCHAR2(15) DEFAULT 'APROBADO' NOT NULL,
  referencia_pasarela VARCHAR2(100),
  CONSTRAINT fk_pago_reserva FOREIGN KEY (id_reserva) REFERENCES reserva (id_reserva),
  CONSTRAINT ck_pago_monto CHECK (monto > 0),
  CONSTRAINT ck_pago_metodo CHECK (metodo_pago IN ('TARJETA','TRANSFERENCIA','EFECTIVO','PSE','WOMPI')),
  CONSTRAINT ck_pago_estado CHECK (estado IN ('PENDIENTE','APROBADO','RECHAZADO','REEMBOLSADO'))
) TABLESPACE ts_historico_reservas;

-- ---------------------------------------------------------------------
-- 11. SERVICIO
-- ---------------------------------------------------------------------
CREATE TABLE servicio (
  id_servicio    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  id_alojamiento NUMBER NOT NULL,
  nombre         VARCHAR2(80) NOT NULL,
  descripcion    VARCHAR2(200),
  precio         NUMBER(10,2) NOT NULL,
  CONSTRAINT fk_servicio_alojamiento FOREIGN KEY (id_alojamiento) REFERENCES alojamiento (id_alojamiento),
  CONSTRAINT ck_servicio_precio CHECK (precio >= 0)
);

-- ---------------------------------------------------------------------
-- 12. RESERVA_SERVICIO
-- ---------------------------------------------------------------------
CREATE TABLE reserva_servicio (
  id_reserva_servicio  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  id_reserva           NUMBER NOT NULL,
  id_servicio          NUMBER NOT NULL,
  cantidad             NUMBER NOT NULL,
  precio_unitario      NUMBER(10,2) NOT NULL,
  CONSTRAINT fk_resserv_reserva FOREIGN KEY (id_reserva) REFERENCES reserva (id_reserva),
  CONSTRAINT fk_resserv_servicio FOREIGN KEY (id_servicio) REFERENCES servicio (id_servicio),
  CONSTRAINT ck_resserv_cantidad CHECK (cantidad > 0),
  CONSTRAINT ck_resserv_precio CHECK (precio_unitario >= 0)
) TABLESPACE ts_historico_reservas;

-- ---------------------------------------------------------------------
-- 13. RESENA  (= "RESEÑA" del enunciado, ver nota de nomenclatura en docs/00_modelo_ER.md)
-- ---------------------------------------------------------------------
CREATE TABLE resena (
  id_resena      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  id_cliente     NUMBER NOT NULL,
  id_alojamiento NUMBER NOT NULL,
  id_reserva     NUMBER,
  calificacion   NUMBER(1) NOT NULL,
  comentario     VARCHAR2(500),
  fecha_resena   DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT fk_resena_cliente FOREIGN KEY (id_cliente) REFERENCES cliente (id_cliente),
  CONSTRAINT fk_resena_alojamiento FOREIGN KEY (id_alojamiento) REFERENCES alojamiento (id_alojamiento),
  CONSTRAINT fk_resena_reserva FOREIGN KEY (id_reserva) REFERENCES reserva (id_reserva),
  CONSTRAINT uq_resena_reserva UNIQUE (id_reserva),
  CONSTRAINT ck_resena_calificacion CHECK (calificacion BETWEEN 1 AND 5)
);

-- ---------------------------------------------------------------------
-- 14. USUARIO_SISTEMA
-- ---------------------------------------------------------------------
CREATE TABLE usuario_sistema (
  id_usuario      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  username        VARCHAR2(30) NOT NULL,
  password_hash   VARCHAR2(200) NOT NULL,
  rol             VARCHAR2(25) NOT NULL,
  id_alojamiento  NUMBER,
  activo          CHAR(1) DEFAULT 'S' NOT NULL,
  fecha_creacion  DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT uq_usuario_username UNIQUE (username),
  CONSTRAINT fk_usuario_alojamiento FOREIGN KEY (id_alojamiento) REFERENCES alojamiento (id_alojamiento),
  CONSTRAINT ck_usuario_rol CHECK (rol IN ('RECEPCION','ADMIN_ALOJAMIENTO','GERENTE','AUDITOR')),
  CONSTRAINT ck_usuario_activo CHECK (activo IN ('S','N'))
);

-- ---------------------------------------------------------------------
-- Índices de apoyo a FKs muy consultadas (no son los de la Entrega 3,
-- esos se justifican con planes de ejecución más adelante)
-- ---------------------------------------------------------------------
CREATE INDEX ix_alojamiento_municipio ON alojamiento (id_municipio);
CREATE INDEX ix_habitacion_alojamiento ON habitacion (id_alojamiento);
CREATE INDEX ix_reserva_cliente ON reserva (id_cliente);
CREATE INDEX ix_reserva_fechas ON reserva (fecha_checkin, fecha_checkout);
CREATE INDEX ix_pago_reserva ON pago (id_reserva);
CREATE INDEX ix_resserv_reserva ON reserva_servicio (id_reserva);

COMMIT;
