-- =====================================================================
-- TurismoUQ — 02_tabla_auditoria.sql (Entrega 2)
-- Tabla donde el disparador de sentencia trg_auditoria_tarifa (ver
-- 04_triggers.sql) registra cada cambio de precio: quién, cuándo,
-- valor anterior y nuevo.
-- Ejecutar conectado como: turismouq@//localhost:1521/XEPDB1
-- =====================================================================

CREATE TABLE auditoria_tarifa (
  id_auditoria    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  id_tarifa       NUMBER NOT NULL,
  usuario_bd      VARCHAR2(30) NOT NULL,
  fecha_cambio    DATE DEFAULT SYSDATE NOT NULL,
  valor_anterior  NUMBER(10,2) NOT NULL,
  valor_nuevo     NUMBER(10,2) NOT NULL,
  CONSTRAINT fk_auditoria_tarifa FOREIGN KEY (id_tarifa) REFERENCES tarifa (id_tarifa)
);
